arch:
    - arm64

language: bash

services:
    - docker

script:
    - 'make test'
    - 'make image'

deploy:
    provider: script
    script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && make push
    on:
        branch: master
        tags: true
