arch:
    - arm64

language: bash

services:
    - docker

script:
    - 'make test'
    - 'make image'

deploy:
    provider: script
    script: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && make push
    on:
        branch: master
